apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260508-234609-xjygg9464m0s-service
spec:
  selector:
    app: enterprise-system-20260508-234609-xjygg9464m0s
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
